=== HerbFargus/bomberstuff/bin/Debug/settings.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		targetNamespace="BomberStuff"
		xmlns="BomberStuff"
		elementFormDefault="qualified">
	
	<xs:element name="Settings">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="String" type="String" />
        <xs:element name="Int" type="Int" />
        <xs:element name="UInt" type="UInt" />
        <xs:element name="NInt" type="NInt" />
				<xs:element name="Size" type="Size" />
				<xs:element name="ColorRemapInfo" type="ColorRemapInfo" />
        <xs:element name="PlayerControls" type="PlayerControls" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="String">
		<xs:simpleContent>
			<xs:extension base="xs:string">
        <xs:attributeGroup ref="SettingsAttributes" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

  <xs:complexType name="Int">
    <xs:simpleContent>
      <xs:extension base="xs:integer">
        <xs:attributeGroup ref="SettingsAttributes" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="UInt">
    <xs:simpleContent>
      <xs:extension base="xs:nonNegativeInteger">
        <xs:attributeGroup ref="SettingsAttributes" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="NInt">
    <xs:simpleContent>
      <xs:extension base="xs:positiveInteger">
        <xs:attributeGroup ref="SettingsAttributes" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
	
	<xs:complexType name="Size">
		<xs:sequence>
			<xs:element name="Width" type="xs:nonNegativeInteger" />
			<xs:element name="Height" type="xs:nonNegativeInteger" />
		</xs:sequence>
    <xs:attributeGroup ref="SettingsAttributes" />
	</xs:complexType>
	
	<xs:complexType name="ColorRemapInfo">
		<xs:sequence>
			<xs:element name="Hue" minOccurs="0" default="135">
				<xs:simpleType>
					<xs:restriction base="xs:nonNegativeInteger">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="359" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Saturation" minOccurs="0" default="">
				<xs:simpleType>
          <xs:union>
            <xs:simpleType>
					    <xs:restriction base="xs:nonNegativeInteger">
						    <xs:minInclusive value="0" />
						    <xs:maxInclusive value="359" />
					    </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:length value="0" />
              </xs:restriction>
            </xs:simpleType>
          </xs:union>
				</xs:simpleType>
			</xs:element>
			<xs:element name="LightnessDifference" minOccurs="0" default="0">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="-359" />
						<xs:maxInclusive value="+359" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
    <xs:attributeGroup ref="SettingsAttributes" />
	</xs:complexType>

  <xs:complexType name="PlayerControls">
    <xs:sequence>
      <xs:element name="Up" type="xs:string" minOccurs="0" />
      <xs:element name="Down" type="xs:string" minOccurs="0" />
      <xs:element name="Left" type="xs:string" minOccurs="0" />
      <xs:element name="Right" type="xs:string" minOccurs="0" />
      <xs:element name="Action1" type="xs:string" minOccurs="0" />
      <xs:element name="Action2" type="xs:string" minOccurs="0" />
    </xs:sequence>
    <xs:attributeGroup ref="SettingsAttributes" />
  </xs:complexType>
	
	<xs:simpleType name="Name">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Za-z]+([.][A-Za-z]+)?"/>
		</xs:restriction>
	</xs:simpleType>

  <xs:attributeGroup name="SettingsAttributes">
    <xs:attribute name="name" type="Name" use="required" />
    <xs:attribute name="index" type="xs:nonNegativeInteger" use="optional" />
  </xs:attributeGroup>
	
</xs:schema>

=== HerbFargus/bomberstuff/bin/Debug/settings.xml
<?xml version="1.0"?>
<Settings xmlns="BomberStuff"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="BomberStuff settings.xsd">
	
  <!-- Set your Atomic Bomberman path here. It should contain a DATA subdirectory-->
  <String name="ABDirectory">
		C:\Temp\atomic_bomberman\bomber
	</String>

  <!-- Currently available option(s): SlimDXInterface, WinFormsInterface -->
  <String name="UserInterface">
    SlimDXInterface
  </String>

  <!-- Window size. You can try other than the suggested values,
       but it might look crappy (gaps and such) -->
  <Size name="WindowSize">
    <!--<Width>640</Width><Height>480</Height>-->
    <Width>1280</Width><Height>960</Height>
    <!--<Width>1600</Width><Height>1200</Height>-->
	</Size>

  <!--
  <!- - No value means random - ->
  <UInt name="Tileset">
    0
  </UInt>-->

  <!-- Anything in the SCHEMES directory. Default is BASIC -->
  <String name="Scheme">
    X
  </String>
  
  <!-- NOTE: most (all?) schemes are limited to 10 players, so
             don't be surprised if large numbers don't work -->
  <NInt name="PlayerCount">
    1
  </NInt>
  
  
  <!-- This is a debug thing. Don't change it or the game won't start -->
	<String name="GotSettings">true</String>
  
  <!--
    Player key bindings
  -->
  <!-- green dude -->
  <PlayerControls name="PlayerControls" index="0">
    <Up>Up</Up>
    <Down>Down</Down>
    <Left>Left</Left>
    <Right>Right</Right>
    <Action1>Q</Action1>
    <Action2>W</Action2>
  </PlayerControls>

  <!-- pink dude -->
  <PlayerControls name="PlayerControls" index="5">
    <Up>P</Up>
    <Down>Oem1</Down> <!-- Semicolon/Ö key-->
    <Left>L</Left>
    <Right>Oem7</Right> <!-- Quotes/Ä key -->
    <Action1>N</Action1>
    <Action2>M</Action2>
  </PlayerControls>

  <!--
    Player Colors
    
    A HSL system is used with H, S and L each in [0,359]
    
    You can set the following:
    - a Hue value (default: 135 = green)
    - Saturation and Lightness difference values (to create bright/dark green, white/black/grey)
    - Hue, Saturation AND Lightness difference (if a color needs S/L adjustment to look good)
  -->
  <ColorRemapInfo name="PlayerColor" index="0">
    <!-- Player 0: unmodified green bomber -->
  </ColorRemapInfo>
  <ColorRemapInfo name="PlayerColor" index="1">
    <!-- Player 1: light blue -->
    <Hue>225</Hue>
  </ColorRemapInfo>
  <ColorRemapInfo name="PlayerColor" index="2">
    <!-- Player 2: yellow -->
    <Hue>75</Hue>
    <Saturation>240</Saturation>
    <LightnessDifference>+20</LightnessDifference>
  </ColorRemapInfo>
  <ColorRemapInfo name="PlayerColor" index="3">
    <!-- Player 3: red -->
    <Hue>0</Hue>
  </ColorRemapInfo>
  <ColorRemapInfo name="PlayerColor" index="4">
    <!-- Player 4: orange -->
    <Hue>45</Hue>
  </ColorRemapInfo>
  <ColorRemapInfo name="PlayerColor" index="5">
    <!-- Player 5: pink -->
    <Hue>315</Hue>
  </ColorRemapInfo>
  <ColorRemapInfo name="PlayerColor" index="6">
    <!-- Player 6: turquoise -->
    <Hue>195</Hue>
  </ColorRemapInfo>
  <ColorRemapInfo name="PlayerColor" index="7">
    <!-- Player 7: white -->
    <Saturation>0</Saturation>
    <LightnessDifference>+150</LightnessDifference>
  </ColorRemapInfo>
  <ColorRemapInfo name="PlayerColor" index="8">
    <!-- Player 8: black -->
    <Saturation>0</Saturation>
    <LightnessDifference>-120</LightnessDifference>
  </ColorRemapInfo>
  <ColorRemapInfo name="PlayerColor" index="9">
    <!-- Player 9: purple -->
    <!-- NOTE: The last entry will be repeated for any additional players -->
    <Hue>285</Hue>
  </ColorRemapInfo>
</Settings>
